version: '3.9'

services:
  frontend:
    container_name: frontend_service
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env

networks:
  backend:
    external: true
    name: net_secured
